# Generated by Django 6.0.4 on 2026-06-19 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenzo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupexpense',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_group_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GroupExpensePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('group_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='expenzo.groupexpense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
