# Generated by Django 6.0.4 on 2026-06-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenzo', '0002_alter_groupexpense_paid_by_groupexpensepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='icon',
            field=models.CharField(blank=True, default='users', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MEMBER', 'Member')], default='MEMBER', max_length=20),
        ),
    ]
