# Generated by Django 6.0.4 on 2026-06-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenzo', '0005_recurringexpense_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='icon',
            field=models.CharField(blank=True, default='users', max_length=255, null=True),
        ),
    ]
