# Generated by Django 6.0.4 on 2026-06-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenzo', '0007_group_icon_base64_userprofile_avatar_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringexpense',
            name='execution_day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='recurringexpense',
            name='last_processed_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurringexpense',
            name='last_processed_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurringincome',
            name='execution_day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='recurringincome',
            name='last_processed_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurringincome',
            name='last_processed_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
